name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)_v$(ExtensionVersion)

trigger: none

stages:
- stage: ExtensionBuild
  displayName: 'Build and pack'
  jobs:
  - job: BuildAndPack
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - template: azure-pipelines/build-steps.yaml
      parameters:
        packQA: true
        publishOutput: true
- template: azure-pipelines/marketplace-publish.yaml
  parameters:
    environment: QA
    vsixFile: '$(Agent.BuildDirectory)/drop/qa/gustavobergamim.pipeline-approval-qa-*.vsix'
    shareWith: 'gustavobergamim vstssprints'
- template: azure-pipelines/marketplace-publish.yaml
  parameters:
    environment: Production
    vsixFile: '$(Agent.BuildDirectory)/drop/prod/gustavobergamim.pipeline-approval-*.vsix'
