name: $(GitVersion.MajorMinorPatch)
trigger: none

stages:
- stage: ExtensionBuild
  displayName: 'Build and pack'
  jobs:
  - job: BuildAndPack
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - task: gittools.gitversion.gitversion-task.GitVersion@5
      displayName: GitVersion
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'
    - script: npm install
      displayName: 'Resolving dependencies'
    - script: npm run package
      displayName: 'Building and packing extension'
    - task: CopyFiles@2
      displayName: Copy vsix files
      inputs:
        sourceFolder: $(Build.SourcesDirectory)/out
        contents: |
          **/*.vsix
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: CopyFiles@2
      displayName: Copy manifest file
      inputs:
        sourceFolder: $(Build.SourcesDirectory)
        contents: |
          vss-extension.json
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: CopyFiles@2
      displayName: Copy config files
      inputs:
        sourceFolder: $(Build.SourcesDirectory)/configs
        contents: |
          **/*.json
        targetFolder: '$(Build.ArtifactStagingDirectory)/configs'
    - task: PublishBuildArtifacts@1
      displayName: 'Publishing artifacts'
- stage: ExtensionPublishQA
  displayName: 'QA Publish'
  jobs:
  - deployment: Publish
    pool:
      vmImage: 'ubuntu-16.04'
    environment: QA
    strategy:
      runOnce:
        deploy:
          steps:
          - task: ms-devlabs.vsts-developer-tools-build-tasks.tfx-installer-build-task.TfxInstaller@2
            displayName: 'Use Node CLI for Azure DevOps (tfx-cli): v0.6.x'
          - task: ms-devlabs.vsts-developer-tools-build-tasks.publish-extension-build-task.PublishAzureDevOpsExtension@2
            displayName: 'Publish Extension'
            inputs:
              connectedServiceName: 'VS MarketPlace'
              fileType: vsix
              vsixFile: '$(Agent.BuildDirectory)/drop/gustavobergamim.pipeline-approval-*.vsix'
              extensionVersion: '$(Build.BuildNumber)'
              arguments: --manifest-globs vss-extension.json --overrides-file configs/qa.json
- stage: ExtensionPublishProduction
  displayName: 'Publish extension to Visual Studio Marketplace'
  jobs:
  - deployment: Publish
    pool:
      vmImage: 'ubuntu-16.04'
    environment: Production
    strategy:
      runOnce:
        deploy:
          steps:
          - task: ms-devlabs.vsts-developer-tools-build-tasks.tfx-installer-build-task.TfxInstaller@2
            displayName: 'Use Node CLI for Azure DevOps (tfx-cli): v0.6.x'
          - task: ms-devlabs.vsts-developer-tools-build-tasks.publish-extension-build-task.PublishAzureDevOpsExtension@2
            displayName: 'Publish Extension'
            inputs:
              connectedServiceName: 'VS MarketPlace'
              fileType: vsix
              vsixFile: '$(Agent.BuildDirectory)/drop/gustavobergamim.pipeline-approval-*.vsix'
              extensionVersion: '$(Build.BuildNumber)'
              arguments: --manifest-globs vss-extension.json --overrides-file configs/release.json
