parameters:
  packQA: false
  publishOutput: false

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'
- script: npm install
  displayName: 'Resolving dependencies'
- task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
  displayName: 'Prepare analysis on SonarCloud'
  inputs:
    SonarCloud: SonarCloud
    organization: azuredevopsextensions
    scannerMode: CLI
- script: npm run compile
  displayName: 'Building'
- script: npm run package:qa
  displayName: 'Packing extension for QA'
  condition: ${{parameters.packQA}}
- script: npm run package:prod
  displayName: 'Packing extension for Production'
- task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'
- task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
  displayName: 'Publish Quality Gate Result'
- task: CopyFiles@2
  displayName: Copy vsix files
  condition: ${{parameters.publishOutput}}
  inputs:
    sourceFolder: $(Build.SourcesDirectory)/out
    contents: |
      **/*.vsix
    targetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publishing artifacts'
  condition: ${{parameters.publishOutput}